### PR TITLE
update: Add Code Upload functionality

### PR DESCRIPTION
**Pull request by mrshu**
* Add Code Upload functionality via Flask-AppBuilder's FileColumn

* Add a custom list template to add a small note on how to upload new
  submissions.

* Update the index to let people know they ought to login first.

* Updated the README a bit

Signed-off-by: mr.Shu <mr@shu.io>

-----------------------------------

cc @RoboCupJuniorTC/soccer-simulator

### CODE REVIEW

**Comment by mrshu** [comment]
@Adman see if you can get this to work locally on your box.

Once you can, I guess we should update that "JS check" of yours to work with this whole framework. It looks fairly extendible, so I have high hopes :)

Thanks!

**Comment by Adman** [comment]
LGTM, but when I uploaded the zip, I cannot find the uploads folder. Shall I create it manually before running the app?

**Review by Adman — APPROVED** [review]

**Comment by mrshu** [comment]
> LGTM, but when I uploaded the zip, I cannot find the uploads folder. Shall I create it manually before running the app?

Hmm, that shouldn't be the case. Is your `app/static/uploads/` really empty?

**Comment by Adman** [comment]
Oh yeah, it's there, thanks :+1: 

Clicking on "Download" it says "Access denied", am I missing some permission?

**Comment by mrshu** [comment]
Hmm, that's strange -- if you have Admin user, it should just work. Is that so?

**Comment by Adman** [comment]
In roles there is `[Admin]`.

**Comment by mrshu** [comment]
Well, that's quite strange (and perhaps even wrong). I honestly don't know how that happens.

**Comment by mrshu** [comment]
Let's get this merged and figure it out in prod ;)

**Pull request merged**
